import {
  BreakfastPlan,
  BreakfastSettings,
  MotherMealDay,
  MotherWorkoutItem,
  MotherSettings,
  TypographySettings,
} from '@/domain/types';

// ================== DEFAULT BREAKFAST PLANS FOR KIDS ==================

export const SEED_BREAKFAST_PLANS: BreakfastPlan[] = [
  {
    id: 'bp-quan-week-a',
    child_id: 'child-trung-quan',
    name: 'Menu Tuần A (Đủ chất)',
    meals: [
      { weekday: 2, meal: 'Phở bò', note: 'Uống thêm 1 hộp sữa tươi' },
      { weekday: 3, meal: 'Bánh mì trứng', note: 'Kèm dưa chuột & phô mai' },
      { weekday: 4, meal: 'Xôi xéo ruốc', note: 'Thêm chả quế' },
      { weekday: 5, meal: 'Bún bò Huế', note: 'Ít cay' },
      { weekday: 6, meal: 'Bánh bao nhân thịt', note: '2 bánh + 1 sữa hạt' },
      { weekday: 7, meal: 'Cơm chiên trứng', note: 'Thêm xúc xích' },
      { weekday: 8, meal: 'Bánh mì chảo', note: 'Bữa sáng cuối tuần' },
    ],
    created_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'bp-quan-week-b',
    child_id: 'child-trung-quan',
    name: 'Menu Tuần B (Đổi vị)',
    meals: [
      { weekday: 2, meal: 'Bún riêu cua', note: 'Thêm thịt bò trần' },
      { weekday: 3, meal: 'Sandwich phô mai', note: 'Uống kèm sữa tươi' },
      { weekday: 4, meal: 'Phở gà', note: 'Đùi gà xé' },
      { weekday: 5, meal: 'Bánh cuốn chả', note: 'Chả quế nóng' },
      { weekday: 6, meal: 'Mì tôm nấu trứng', note: 'Thêm rau cải & thịt băm' },
      { weekday: 7, meal: 'Xôi lạc đậu xanh', note: 'Kèm muối vừng & ruốc' },
      { weekday: 8, meal: 'Hủ tiếu Nam Vang', note: 'Cuối tuần cả nhà' },
    ],
    created_at: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'bp-bang-week-a',
    child_id: 'child-ha-bang',
    name: 'Menu Tuần A (Bé Băng)',
    meals: [
      { weekday: 2, meal: 'Cháo sườn / cháo gà', note: 'Uống 1 hộp sữa công thức' },
      { weekday: 3, meal: 'Bánh bao nhân thịt', note: 'Nhân thịt trứng cút mềm' },
      { weekday: 4, meal: 'Ngũ cốc + sữa tươi', note: 'Thêm chuối chín' },
      { weekday: 5, meal: 'Bánh cuốn chả', note: 'Cắt nhỏ dễ ăn' },
      { weekday: 6, meal: 'Phở gà', note: 'Cắt nhỏ bánh phở' },
      { weekday: 7, meal: 'Sandwich phô mai', note: 'Áp chảo mềm + sữa tươi' },
      { weekday: 8, meal: 'Sữa chua + hoa quả', note: 'Kèm bánh trứng mềm' },
    ],
    created_at: '2026-09-01T00:00:00.000Z',
  },
];

export const SEED_BREAKFAST_SETTINGS: BreakfastSettings[] = [
  {
    child_id: 'child-trung-quan',
    enabled: true,
    active_plan_id: 'bp-quan-week-a',
    auto_rotate: true,
    cycle_start: '2026-09-28',
  },
  {
    child_id: 'child-ha-bang',
    enabled: true,
    active_plan_id: 'bp-bang-week-a',
    auto_rotate: false,
    cycle_start: '2026-09-28',
  },
];

// ================== THỰC ĐƠN 30 NGÀY CỦA MẸ (Mother_Menu.md - 1300 Calo - Đinh Thị Mơ) ==================

export const MOTHER_GOLDEN_RULES: string[] = [
  '💧 Uống đủ 2 Lít nước mỗi ngày (khoảng 8 cốc nước 250ml trải đều từ sáng đến tối).',
  '🥬 Rau lá ăn thoải mái không cần đúng định lượng; nhưng các loại củ quả phải ăn đúng lượng vì có nhiều tinh bột.',
  '⚖️ Thịt cá và Cơm khoai bắt buộc ăn đúng định lượng: Cơm, khoai cân CHÍN — Thịt, cá, tôm cân SỐNG.',
  '🍳 Có thể thay đổi cách chế biến xào, nấu, luộc, hấp tùy thích để không bị chán. Xào nấu với nước lọc ướp gia vị hoặc dùng dầu xịt 0 calo.',
  '🧂 Ăn gia vị mắm, muối, tiêu, ớt bình thường nhưng vừa phải (ăn mặn quá sẽ bị tích nước). Dùng đường ăn kiêng 0 calo thay thế đường thường.',
  '🍚 Mẹo chuẩn bị: Gạo lứt nấu 1 nồi to rồi chia mỗi bọc 100g–150g cho vào tủ đá, khi ăn hấp lại ăn dần (ưu tiên gạo lứt hơn gạo trắng, nhưng không bắt buộc bỏ gạo trắng).',
  '🥒 Khi đói giữa giờ: Chuẩn bị sẵn củ đậu, dưa chuột ăn một chút hoặc nấu thêm thạch sương sáo không đường / đường ăn kiêng.',
];

export const SEED_MOTHER_MEAL_DAYS: MotherMealDay[] = [
  {
    day: 1,
    breakfast: '2 lát Sandwich + 1 Trứng + 1 dưa chuột',
    lunch: '170g Khoai lang + 150g Cá + 150g rau',
    snack: '1 quả Táo',
    dinner: '150g Cơm chín + 130g Bò + 150g rau',
    note: 'Rau có thể ăn rau tùy thích nhưng phải là dòng rau lá. Các loại củ quả phải ăn đúng lượng vì trong củ quả có nhiều tinh bột.',
  },
  {
    day: 2,
    breakfast: '1 bắp ngô + 1 hộp sữa tươi ko đường',
    lunch: '150g Cơm chín + 150g Ức gà + 200g rau',
    snack: '20g Hạt',
    dinner: '170g Khoai lang + 130g Tôm + 150g rau',
    note: 'Chuẩn bị củ đậu, dưa chuột ăn 1 chút lúc đói. Nấu thêm thạch sương sáo ko đường hoặc đường ăn kiêng.',
  },
  {
    day: 3,
    breakfast: '40g Yến mạch + 200ml Sữa',
    lunch: '250g Bí đỏ + 130g Bò + rau',
    snack: '1 Sữa chua',
    dinner: '150g Cơm chín + 150g Heo nạc + 200g rau',
    note: 'Nấu ăn gia vị mắm muối vừa phải, ăn mặn quá bị tích nước. Dùng đường ăn kiêng 0 calo thay thế, ko dùng dầu hoặc dùng dầu xịt 0 calo.',
  },
  {
    day: 4,
    breakfast: '1 Trứng + 130g khoai',
    lunch: '150g Cơm chín + 150g Tôm + 200g rau',
    snack: '1 quả Chuối',
    dinner: '170g Ngô + 150g Cá + 200g rau',
    note: 'Gạo lứt nấu 1 nồi to rồi bọc mỗi bọc 100g cho tủ đá khi ăn hấp lại ăn dần (gạo lứt tốt hơn gạo trắng trong giảm cân nhưng ko nhất thiết bỏ gạo trắng).',
  },
  {
    day: 5,
    breakfast: 'Phở gà bỏ da (1/3 bánh, 1/3 nước)',
    lunch: '170g Khoai lang + 150g Heo nạc + 150g rau',
    snack: '20g Hạt',
    dinner: '150g Cơm chín + 150g Ức gà + 150g rau',
    note: 'Số lượng thực phẩm có sẵn, chế biến sao cho dễ ăn nhất là được, ko nhất thiết ăn luộc sẽ bị nhanh chán. Xào nấu với nước lọc ướp gia vị sẽ ngon hơn.',
  },
  {
    day: 6,
    breakfast: '250g Bí đỏ + 1 Trứng',
    lunch: '150g Cơm chín + 2 bìa Đậu phụ + rau',
    snack: '1 Sữa chua',
    dinner: '170g Ngô + 150g Heo nạc + 150g rau',
  },
  {
    day: 7,
    breakfast: '2 lát Sandwich + 70g Bò',
    lunch: '170g Ngô + 150g Cá + 200g rau',
    snack: '20g Hạt',
    dinner: '150g Cơm chín + 150g Ức gà xào nấm',
  },
  {
    day: 8,
    breakfast: '40g Yến mạch + 1 Sữa chua',
    lunch: '150g Cơm chín + 150g Heo nạc + 150g rau',
    snack: '200ml Sữa',
    dinner: '170g Khoai lang + 130g Bò + 150g rau',
  },
  {
    day: 9,
    breakfast: '1 Trứng + 1 Sữa tươi',
    lunch: '250g Bí đỏ + 150g Ức gà luộc',
    snack: '1 quả Cam',
    dinner: '150g Cơm chín + 150g Cá + 200g rau',
  },
  {
    day: 10,
    breakfast: '170g Khoai lang + 1 Sữa tươi',
    lunch: '150g Cơm chín + 130g Bò + 150g rau',
    snack: '20g Hạt',
    dinner: '1 bát phở bò (1/2 bánh, ít nước)',
  },
  {
    day: 11,
    breakfast: '2 lát Sandwich + 1 Trứng + dưa chuột',
    lunch: '170g Khoai lang + 150g Tôm + 200g rau',
    snack: '1 Sữa chua',
    dinner: '150g Cơm chín + 150g Heo nạc + 150g rau',
  },
  {
    day: 12,
    breakfast: '40g Yến mạch + 200ml Sữa',
    lunch: '150g Cơm chín + 150g Cá + 200g rau',
    snack: '1 quả Ổi',
    dinner: '250g Bí đỏ + 150g Ức gà xào nấm',
  },
  {
    day: 13,
    breakfast: '120g Khoai lang + 1 Trứng',
    lunch: '150g Cơm chín + 130g Heo nạc + 150g rau',
    snack: '20g Hạt',
    dinner: '150g Cơm chín + 130g Bò + 150g rau',
  },
  {
    day: 14,
    breakfast: '170g Khoai lang + 1 Sữa chua',
    lunch: '150g Cơm chín + 150g Ức gà + 200g rau',
    snack: '1 quả Chuối',
    dinner: '170g Ngô + 150g Tôm + 200g rau',
  },
  {
    day: 15,
    breakfast: 'Bát phở bò (1/2 bánh, thịt nạc)',
    lunch: '170g Khoai lang + 150g Cá + 200g rau',
    snack: '1 Sữa chua',
    dinner: '150g Cơm chín + 2 bìa Đậu phụ + rau',
  },
  {
    day: 16,
    breakfast: '2 lát Sandwich + 1 Trứng + dưa chuột',
    lunch: '150g Cơm chín + 150g Tôm + 200g rau',
    snack: '20g Hạt',
    dinner: '170g Khoai lang + 150g Ức gà luộc',
  },
  {
    day: 17,
    breakfast: '40g Yến mạch + 100ml Sữa tươi',
    lunch: '150g cơm + 130g Bò xào ớt chuông',
    snack: '1 hũ Sữa chua',
    dinner: '150g Cơm chín + 130g Bò + 150g rau',
  },
  {
    day: 18,
    breakfast: '250g Bí đỏ + 1 Trứng',
    lunch: '150g Cơm chín + 150g Heo nạc + 150g rau',
    snack: '1 quả Táo',
    dinner: '170g Khoai lang + 150g Tôm + 200g rau',
  },
  {
    day: 19,
    breakfast: '170g Khoai lang + 1 Sữa tươi',
    lunch: '150g Cơm chín + 150g Ức gà + 200g rau',
    snack: '1 Sữa chua',
    dinner: '150g Cơm chín + 150g Cá + 200g rau',
  },
  {
    day: 20,
    breakfast: '2 lát Sandwich + 1 Trứng + dưa chuột',
    lunch: 'Phở gà (1/3 bánh, 1/3 nước)',
    snack: '20g Hạt',
    dinner: '150g Cơm chín + 150g Heo nạc + 150g rau',
  },
  {
    day: 21,
    breakfast: '40g Yến mạch + 1 Sữa chua',
    lunch: '170g Khoai lang + 130g Bò + 150g rau',
    snack: '1 ly Sữa',
    dinner: '250g Bí đỏ + 150g Tôm + rau',
  },
  {
    day: 22,
    breakfast: '1 Trứng + 1 bắp Ngô',
    lunch: '150g Cơm chín + 150g Cá + 200g rau',
    snack: '1 quả Ổi',
    dinner: '170g Khoai lang + 150g Ức gà',
  },
  {
    day: 23,
    breakfast: '30g Yến mạch nấu cháo + 3 con tôm',
    lunch: '150g Cơm chín + 150g Heo nạc + 150g rau',
    snack: '1 Sữa chua',
    dinner: '150g Cơm chín + 2 bìa Đậu phụ + rau',
  },
  {
    day: 24,
    breakfast: '250g Bí đỏ + 1 Sữa tươi + dưa chuột',
    lunch: '150g Cơm chín + 150g Ức gà + 150g rau',
    snack: '20g Hạt',
    dinner: '170g Khoai lang + 130g Tôm + 200g rau',
  },
  {
    day: 25,
    breakfast: '1 quả chuối + 1 sữa hạt',
    lunch: '170g Khoai lang + 150g Cá + 200g rau',
    snack: '1 quả Chuối',
    dinner: '150g Cơm chín + 130g Ức gà + 150g rau',
  },
  {
    day: 26,
    breakfast: '40g Yến mạch + 40g thịt nạc nấu cháo',
    lunch: '150g Cơm chín + 130g Bò + 200g rau',
    snack: '200ml Sữa',
    dinner: '100g cơm + 150g Heo nạc + 150g rau',
  },
  {
    day: 27,
    breakfast: '2 lát Sandwich + 1 Trứng + dưa chuột',
    lunch: '170g Khoai lang + 150g Tôm + 200g rau',
    snack: '1 quả Táo',
    dinner: '150g Cơm chín + 150g Cá + 150g rau',
  },
  {
    day: 28,
    breakfast: '1 lát bánh mì + 1 trứng chiên + dưa',
    lunch: '150g Cơm chín + 150g Đùi gà + 150g rau',
    snack: '1 Sữa chua',
    dinner: '250g Bí đỏ + 130g Heo nạc + 150g rau',
  },
  {
    day: 29,
    breakfast: '2 quả trứng luộc',
    lunch: '170g Khoai lang + 130g Bò + 200g rau',
    snack: '20g Hạt',
    dinner: '150g Cơm chín + 2 bìa Đậu phụ + rau',
  },
  {
    day: 30,
    breakfast: 'Phở gà (1/3 bánh, 1/3 nước)',
    lunch: '150g Cơm chín + 130g Tôm + rau',
    snack: '1 Sữa chua',
    dinner: '170g Khoai lang + 150g Cá + 200g rau',
  },
];

// ================== LỊCH TẬP LUYỆN HÀNG TUẦN CỦA MẸ ==================

export const SEED_MOTHER_WORKOUTS: MotherWorkoutItem[] = [
  {
    id: 'mw-mon',
    weekday: 2,
    title: 'Cardio Đốt Mỡ & Làm Nóng Toàn Thân',
    category: 'cardio',
    time_slot: '17:30 – 18:15',
    duration_min: 45,
    calories_est: 280,
    exercises: 'Khởi động 5p • Đi bộ nhanh / Chạy bộ nhẹ 25p • Jumping Jacks & Nâng cao đùi 10p • Giãn cơ 5p',
    note: 'Uống 250ml nước trước khi tập 20 phút',
  },
  {
    id: 'mw-tue',
    weekday: 3,
    title: 'Tập Cơ Bụng (Core) & Thân Dưới Săn Chắc',
    category: 'strength',
    time_slot: '17:30 – 18:15',
    duration_min: 45,
    calories_est: 240,
    exercises: 'Squat 3x15 • Lunge 3x12 mỗi chân • Glute Bridge 3x15 • Plank 3x45s • Gập bụng Crunch 3x15',
    note: 'Siết chặt cơ bụng và thở đều khi thực hiện',
  },
  {
    id: 'mw-wed',
    weekday: 4,
    title: 'Yoga Dẻo Dai & Thư Giãn Cột Sống',
    category: 'yoga',
    time_slot: '06:00 – 06:45',
    duration_min: 45,
    calories_est: 180,
    exercises: 'Chuỗi Chào Mặt Trời 10p • Tư thế Chiến Binh & Tam Giác 20p • Giãn cơ lưng, vai gáy & Hít thở sâu 15p',
    note: 'Giúp cơ thể phục hồi và ngủ ngon hơn',
  },
  {
    id: 'mw-thu',
    weekday: 5,
    title: 'HIIT Nhẹ & Thon Gọn Tay Vai - Lưng',
    category: 'hiit',
    time_slot: '17:30 – 18:10',
    duration_min: 40,
    calories_est: 300,
    exercises: 'Tabata đốt mỡ 15p • Tập tạ tay nhẹ (1-2kg) săn bắp tay & vai 15p • Plank nghiêng giảm mỡ eo 10p',
    note: 'Cường độ vừa sức, nghỉ 30s giữa các hiệp',
  },
  {
    id: 'mw-fri',
    weekday: 6,
    title: 'Pilates Định Hình Vóc Dáng & Eo Thon',
    category: 'pilates',
    time_slot: '17:30 – 18:15',
    duration_min: 45,
    calories_est: 230,
    exercises: 'Pilates Hundred • Leg Circles • Tư thế Cây Cầu • Động tác thu gọn vòng eo & hông',
    note: 'Tập trung kiểm soát nhịp thở và cơ lõi',
  },
  {
    id: 'mw-sat',
    weekday: 7,
    title: 'Vận Động Cuối Tuần (Đi Bộ / Đạp Xe / Cầu Lông)',
    category: 'cardio',
    time_slot: '06:30 – 07:30',
    duration_min: 60,
    calories_est: 320,
    exercises: 'Đi bộ công viên / Đạp xe hoặc chơi cầu lông cùng các con ngoài trời',
    note: 'Vừa vận động đốt calo vừa gắn kết gia đình',
  },
  {
    id: 'mw-sun',
    weekday: 8,
    title: 'Nghỉ Ngơi Phục Hồi Cơ & Giãn Cơ Nhẹ',
    category: 'rest',
    time_slot: 'Linh hoạt',
    duration_min: 20,
    calories_est: 100,
    exercises: 'Giãn cơ nhẹ nhàng 15-20p trước khi đi ngủ • Chuẩn bị thực phẩm (Meal Prep) cho tuần mới',
    note: 'Cơ bắp cần ngày nghỉ để phục hồi và săn chắc',
  },
];

export const DEFAULT_MOTHER_SETTINGS: MotherSettings = {
  startDate: '2026-09-28',
  targetCalories: 1300,
  targetWaterLiters: 2.0,
  targetWeightKg: 52,
  currentWeightKg: 56,
  heightCm: 160,
  birthYear: 1990,
  date_of_birth: '1990-10-20',
  authorName: 'Mẹ Yêu',
  nickname: 'Mẹ Quân & Băng',
  avatarUrl: '🧘‍♀️',
  color: '#F43F5E',
  goalNote: 'Giữ dáng thon gọn, khỏe mạnh & tràn đầy năng lượng mỗi ngày',
};

// ================== DEFAULT TYPOGRAPHY SETTINGS ==================

export const DEFAULT_TYPOGRAPHY_SETTINGS: TypographySettings = {
  displayMode: 'auto',
  fullWidthOnLargeScreen: true,
  sections: {
    general: { fontFamily: 'Quicksand', fontSize: 'lg' },
    timetable: { fontFamily: 'Be Vietnam Pro', fontSize: 'lg' },
    breakfast: { fontFamily: 'Be Vietnam Pro', fontSize: 'lg' },
    extra: { fontFamily: 'Quicksand', fontSize: 'lg' },
    kidCorner: { fontFamily: 'Quicksand', fontSize: 'lg' },
    mother: { fontFamily: 'Be Vietnam Pro', fontSize: 'lg' },
  },
};
