import {
  Child,
  TimetableTemplate,
  TimetableEntry,
  ExtraSchedule,
  ScheduleException,
  AssessmentPlan,
  Assessment,
  PerformanceTarget,
  AchievementRecord,
  SchoolYearRecord,
  TeacherContact,
  SubjectItem,
  TimetableLegendItem,
  ExtraClassSessionLog,
  HomeworkTask,
  DailyTeacherComment,
  AcademicMilestone,
} from '@/domain/types';

export const SEED_CHILDREN: Child[] = [
  {
    id: 'child-trung-quan',
    name: 'Trung Quân',
    nickname: 'Quân',
    birthYear: 2013,
    date_of_birth: '2013-08-15',
    school_name: 'THCS Tô Hiệu',
    grade: 'Lớp 8',
    class_name: '8A5',
    avatar_url: 'boy',
    color: '#2563EB',
    active: true,
  },
  {
    id: 'child-ha-bang',
    name: 'Bé Hạ Băng',
    nickname: 'Băng',
    birthYear: 2023,
    date_of_birth: '2023-04-20',
    school_name: 'Trường Mầm Non Họa Mi',
    grade: 'Mầm non 3 tuổi',
    class_name: 'Lớp Mầm 1',
    avatar_url: 'girl',
    color: '#EC4899',
    active: true,
  },
];

export const SEED_TIMETABLE_TEMPLATES: TimetableTemplate[] = [
  {
    id: 'template-quan-hk1',
    child_id: 'child-trung-quan',
    name: 'Thời Khóa Biểu Lớp 6A5 — HK1',
    description: 'Áp dụng cho học kỳ 1 năm học 2026–2027 tại THCS Tô Hiệu',
    school_year: '2026-2027',
    semester: 'HK1',
    valid_from: '2026-09-01',
    valid_to: '2026-12-31',
    status: 'active',
  },
  {
    id: 'template-bang-mn',
    child_id: 'child-ha-bang',
    name: 'Lịch Sinh Hoạt & Năng Khiếu Mầm Non',
    description: 'Lịch sinh hoạt và học năng khiếu tại trường mầm non và tại nhà',
    school_year: '2026-2027',
    semester: 'Cả năm',
    valid_from: '2026-09-01',
    valid_to: '2027-05-31',
    status: 'active',
  },
];

export const SEED_TIMETABLE_ENTRIES: TimetableEntry[] = [
  // ==================== BÉ TRUNG QUÂN - LỚP 6A5 (MATCHING SAMPLE.PNG) ====================
  // --- THỨ 2 (weekday: 2) ---
  // Sáng
  { id: 't2-s1', timetable_id: 'template-quan-hk1', weekday: 2, period: 1, session: 'morning', start_time: '07:00', end_time: '07:45', subject: 'Chào cờ', teacher: 'M. Dung' },
  { id: 't2-s2', timetable_id: 'template-quan-hk1', weekday: 2, period: 2, session: 'morning', start_time: '08:45', end_time: '09:30', subject: 'Ngữ văn', teacher: 'Hiếu' },
  { id: 't2-s3', timetable_id: 'template-quan-hk1', weekday: 2, period: 3, session: 'morning', start_time: '09:50', end_time: '10:35', subject: 'GDTC', teacher: 'Lê Minh' },
  { id: 't2-s4', timetable_id: 'template-quan-hk1', weekday: 2, period: 4, session: 'morning', start_time: '10:55', end_time: '11:40', subject: 'Âm nhạc', teacher: 'Lê Minh' },
  // Chiều
  { id: 't2-c1', timetable_id: 'template-quan-hk1', weekday: 2, period: 1, session: 'afternoon', start_time: '13:30', end_time: '14:15', subject: 'TANN', teacher: 'G.VNN*' },
  { id: 't2-c2', timetable_id: 'template-quan-hk1', weekday: 2, period: 2, session: 'afternoon', start_time: '14:35', end_time: '15:20', subject: 'KNS', teacher: 'M. Dung*' },

  // --- THỨ 3 (weekday: 3) ---
  // Sáng
  { id: 't3-s1', timetable_id: 'template-quan-hk1', weekday: 3, period: 1, session: 'morning', start_time: '07:00', end_time: '07:45', subject: 'Toán', teacher: 'Q. Quyên' },
  { id: 't3-s2', timetable_id: 'template-quan-hk1', weekday: 3, period: 2, session: 'morning', start_time: '08:45', end_time: '09:30', subject: 'Anh', teacher: 'H. Thủy' },
  { id: 't3-s3', timetable_id: 'template-quan-hk1', weekday: 3, period: 3, session: 'morning', start_time: '09:50', end_time: '10:35', subject: 'KHTN (S)', teacher: 'Yên Hoa (TG)' },
  { id: 't3-s4', timetable_id: 'template-quan-hk1', weekday: 3, period: 4, session: 'morning', start_time: '10:55', end_time: '11:40', subject: 'CN', teacher: 'H. Thủy' },
  // Chiều
  { id: 't3-c1', timetable_id: 'template-quan-hk1', weekday: 3, period: 1, session: 'afternoon', start_time: '13:30', end_time: '14:15', subject: 'LS-ĐL (Sử)', teacher: 'Tăm' },
  { id: 't3-c2', timetable_id: 'template-quan-hk1', weekday: 3, period: 2, session: 'afternoon', start_time: '14:35', end_time: '15:20', subject: 'GDTC', teacher: 'Lê Minh' },
  { id: 't3-c3', timetable_id: 'template-quan-hk1', weekday: 3, period: 3, session: 'afternoon', start_time: '15:40', end_time: '16:25', subject: 'Địa', teacher: 'M. Dung' },

  // --- THỨ 4 (weekday: 4) ---
  // Sáng
  { id: 't4-s1', timetable_id: 'template-quan-hk1', weekday: 4, period: 1, session: 'morning', start_time: '07:00', end_time: '07:45', subject: 'GDĐP', teacher: 'Thu Hương' },
  { id: 't4-s2', timetable_id: 'template-quan-hk1', weekday: 4, period: 2, session: 'morning', start_time: '08:45', end_time: '09:30', subject: 'Toán', teacher: 'Q. Quyên' },
  { id: 't4-s3', timetable_id: 'template-quan-hk1', weekday: 4, period: 3, session: 'morning', start_time: '09:50', end_time: '10:35', subject: 'Anh', teacher: 'H. Thủy' },
  { id: 't4-s4', timetable_id: 'template-quan-hk1', weekday: 4, period: 4, session: 'morning', start_time: '10:55', end_time: '11:40', subject: 'KHTN (Lí)', teacher: 'Q. Quyên' },
  // Chiều
  { id: 't4-c1', timetable_id: 'template-quan-hk1', weekday: 4, period: 1, session: 'afternoon', start_time: '13:30', end_time: '14:15', subject: 'HĐTN', teacher: 'Hiếu' },
  { id: 't4-c2', timetable_id: 'template-quan-hk1', weekday: 4, period: 2, session: 'afternoon', start_time: '14:35', end_time: '15:20', subject: 'Ngữ văn', teacher: 'Hiếu' },
  { id: 't4-c3', timetable_id: 'template-quan-hk1', weekday: 4, period: 3, session: 'afternoon', start_time: '15:40', end_time: '16:25', subject: 'Tin', teacher: 'K. Trang' },

  // --- THỨ 5 (weekday: 5) ---
  // Sáng
  { id: 't5-s1', timetable_id: 'template-quan-hk1', weekday: 5, period: 1, session: 'morning', start_time: '07:00', end_time: '07:45', subject: 'GDCD', teacher: 'Q. Quyên' },
  { id: 't5-s2', timetable_id: 'template-quan-hk1', weekday: 5, period: 2, session: 'morning', start_time: '08:45', end_time: '09:30', subject: 'Mĩ thuật', teacher: 'Hiếu' },
  { id: 't5-s3', timetable_id: 'template-quan-hk1', weekday: 5, period: 3, session: 'morning', start_time: '09:50', end_time: '10:35', subject: 'KHTN (S)', teacher: 'Yên Hoa (TG)' },
  { id: 't5-s4', timetable_id: 'template-quan-hk1', weekday: 5, period: 4, session: 'morning', start_time: '10:55', end_time: '11:40', subject: 'Anh', teacher: 'H. Thủy' },
  // Chiều
  { id: 't5-c1', timetable_id: 'template-quan-hk1', weekday: 5, period: 1, session: 'afternoon', start_time: '13:30', end_time: '14:15', subject: 'Ngữ văn', teacher: 'Hiếu' },
  { id: 't5-c2', timetable_id: 'template-quan-hk1', weekday: 5, period: 2, session: 'afternoon', start_time: '14:35', end_time: '15:20', subject: 'Ngữ văn', teacher: 'Hiếu' },
  { id: 't5-c3', timetable_id: 'template-quan-hk1', weekday: 5, period: 3, session: 'afternoon', start_time: '15:40', end_time: '16:25', subject: 'Toán', teacher: 'Q. Quyên' },

  // --- THỨ 6 (weekday: 6) ---
  // Sáng
  { id: 't6-s1', timetable_id: 'template-quan-hk1', weekday: 6, period: 1, session: 'morning', start_time: '07:00', end_time: '07:45', subject: 'Địa', teacher: 'M. Dung' },
  { id: 't6-s2', timetable_id: 'template-quan-hk1', weekday: 6, period: 2, session: 'morning', start_time: '08:45', end_time: '09:30', subject: 'Toán', teacher: 'Q. Quyên' },
  { id: 't6-s3', timetable_id: 'template-quan-hk1', weekday: 6, period: 3, session: 'morning', start_time: '09:50', end_time: '10:35', subject: 'KHTN (Lí)', teacher: 'Quyên' },
  { id: 't6-s4', timetable_id: 'template-quan-hk1', weekday: 6, period: 4, session: 'morning', start_time: '10:55', end_time: '11:40', subject: 'SHL', teacher: 'M. Dung' },

  // ==================== BÉ HẠ BĂNG - MẦM NON 3 TUỔI ====================
  // Thứ 2 đến Thứ 6: Lịch sinh hoạt mầm non
  ...([2, 3, 4, 5, 6] as (2 | 3 | 4 | 5 | 6)[]).flatMap((weekday) => [
    { id: `bang-t${weekday}-s1`, timetable_id: 'template-bang-mn', weekday, period: 1, session: 'morning' as const, start_time: '07:30', end_time: '08:30', subject: 'Đón trẻ & Thể dục sáng', teacher: 'Cô Mai' },
    { id: `bang-t${weekday}-s2`, timetable_id: 'template-bang-mn', weekday, period: 2, session: 'morning' as const, start_time: '08:45', end_time: '09:30', subject: weekday % 2 === 0 ? 'Tạo hình & Vẽ màu' : 'Vận động & Âm nhạc', teacher: 'Cô Mai' },
    { id: `bang-t${weekday}-s3`, timetable_id: 'template-bang-mn', weekday, period: 3, session: 'morning' as const, start_time: '09:45', end_time: '10:30', subject: 'Vui chơi ngoài trời', teacher: 'Cô Lan' },
    { id: `bang-t${weekday}-c1`, timetable_id: 'template-bang-mn', weekday, period: 1, session: 'afternoon' as const, start_time: '14:30', end_time: '15:15', subject: 'Ăn xế & Hoạt động góc', teacher: 'Cô Mai' },
    { id: `bang-t${weekday}-c2`, timetable_id: 'template-bang-mn', weekday, period: 2, session: 'afternoon' as const, start_time: '15:30', end_time: '16:30', subject: 'Kể chuyện & Trả trẻ', teacher: 'Cô Lan' },
  ]),
];

export const SEED_EXTRA_SCHEDULES: ExtraSchedule[] = [
  // Bé Trung Quân - Extra Classes matching sample.png bottom banner
  {
    id: 'extra-quan-math',
    child_id: 'child-trung-quan',
    name: 'Toán bồi dưỡng',
    category: 'math',
    weekdays: [2, 5], // Thứ 2, Thứ 5
    session: 'evening',
    start_time: '19:15',
    end_time: '21:15',
    note: 'Lớp nâng cao cô Quyên',
    color: '#059669',
    fee_per_session: 150000,
    active: true,
  },
  {
    id: 'extra-quan-english',
    child_id: 'child-trung-quan',
    name: 'Tiếng Anh giao tiếp & ngữ pháp',
    category: 'english',
    weekdays: [4, 7], // Thứ 4, Thứ 7
    session: 'evening',
    start_time: '17:15',
    end_time: '19:15',
    note: 'Thứ 4: 17:15–19:15 | Thứ 7: 19:30–21:30',
    color: '#DB2777',
    fee_per_session: 200000,
    active: true,
  },
  {
    id: 'extra-quan-english-tutor',
    child_id: 'child-trung-quan',
    name: 'Phụ đạo Tiếng Anh',
    category: 'english',
    weekdays: [6], // Thứ 6
    session: 'evening',
    start_time: '19:30',
    end_time: '21:30',
    note: '19:30–21:30 hoặc Chủ nhật 8:00–10:00 (nếu không học T6)',
    color: '#7C3AED',
    fee_per_session: 250000,
    active: true,
  },

  // Bé Hạ Băng - Năng khiếu mầm non
  {
    id: 'extra-bang-dance',
    child_id: 'child-ha-bang',
    name: 'Múa thiếu nhi & Cảm thụ âm nhạc',
    category: 'art_pe',
    weekdays: [3, 5], // Thứ 3, Thứ 5
    session: 'evening',
    start_time: '17:45',
    end_time: '18:45',
    note: 'Cung Thiếu nhi Quận',
    color: '#EC4899',
    fee_per_session: 120000,
    active: true,
  },
  {
    id: 'extra-bang-swim',
    child_id: 'child-ha-bang',
    name: 'Bơi làm quen nước cùng ba mẹ',
    category: 'art_pe',
    weekdays: [7], // Thứ 7
    session: 'morning',
    start_time: '08:30',
    end_time: '09:30',
    note: 'Hồ bơi thiếu nhi',
    color: '#0284C7',
    fee_per_session: 150000,
    active: true,
  },
];

export const SEED_SCHEDULE_EXCEPTIONS: ScheduleException[] = [
  {
    id: 'exc-quan-1',
    child_id: 'child-trung-quan',
    date: '2026-09-23', // Thứ 4
    type: 'replace',
    subject: 'Khảo sát giữa HK1 - Toán',
    teacher: 'Hội đồng thi',
    start_time: '08:45',
    end_time: '09:30',
    note: 'Kiểm tra khảo sát tập trung',
  },
  {
    id: 'exc-quan-2',
    child_id: 'child-trung-quan',
    date: '2026-10-05',
    type: 'cancel',
    subject: 'Toán bồi dưỡng',
    note: 'Nghỉ học thêm theo lịch giáo viên bận',
  },
];

export const SEED_ASSESSMENT_PLANS: AssessmentPlan[] = [
  {
    id: 'plan-quan-survey-1',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    grade: 'Lớp 6',
    name: 'Khảo sát đầu năm học 2026–2027',
    type: 'diagnostic',
    planned_date: '2026-09-23',
    description: 'Đánh giá năng lực đầu năm khối 6 các môn Toán, Văn, Anh',
    status: 'completed',
  },
  {
    id: 'plan-quan-midterm-1',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    grade: 'Lớp 6',
    name: 'Kiểm tra Giữa Học kỳ 1',
    type: 'midterm',
    planned_date: '2026-11-05',
    description: 'Thi giữa kỳ tập trung theo đề chung trường THCS Tô Hiệu',
    status: 'planned',
  },
];

export const SEED_ASSESSMENTS: Assessment[] = [
  {
    id: 'assess-quan-survey-1',
    assessment_plan_id: 'plan-quan-survey-1',
    child_id: 'child-trung-quan',
    actual_date: '2026-09-23',
    overall_score: 8.8,
    overall_target: 8.5,
    rank: 5,
    rank_scope: 'Lớp 6A5',
    rank_total: 41,
    percentile: 88,
    comment: 'Khởi đầu năm học rất tốt, phát huy tốt ở môn Tiếng Anh và KHTN!',
    status: 'completed',
    results: [
      { id: 'res-1', assessment_id: 'assess-quan-survey-1', subject: 'Toán', score: 8.5, max_score: 10, target_score: 8.5, previous_score: 8.0, rank: 6, comment: 'Làm bài chắc chắn' },
      { id: 'res-2', assessment_id: 'assess-quan-survey-1', subject: 'Ngữ văn', score: 8.0, max_score: 10, target_score: 8.0, previous_score: 7.8, rank: 9, comment: 'Ý tứ mạch lạc, chữ viết đẹp' },
      { id: 'res-3', assessment_id: 'assess-quan-survey-1', subject: 'Tiếng Anh', score: 9.5, max_score: 10, target_score: 9.0, previous_score: 9.0, rank: 2, comment: 'Từ vựng và ngữ pháp xuất sắc' },
      { id: 'res-4', assessment_id: 'assess-quan-survey-1', subject: 'KHTN', score: 9.0, max_score: 10, target_score: 8.5, previous_score: 8.5, rank: 4, comment: 'Hiểu bài sâu' },
    ],
  },
];

export const SEED_PERFORMANCE_TARGETS: PerformanceTarget[] = [
  {
    id: 'target-quan-math',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    semester: 'HK1',
    subject: 'Toán',
    target_type: 'score',
    target_value: 9.0,
    note: 'Mục tiêu kiểm tra cuối kỳ đạt 9.0 trở lên',
    status: 'in_progress',
  },
  {
    id: 'target-quan-english',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    semester: 'HK1',
    subject: 'Tiếng Anh',
    target_type: 'score',
    target_value: 9.2,
    note: 'Duy trì top 3 lớp môn Tiếng Anh',
    status: 'in_progress',
  },
  {
    id: 'target-quan-literature',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    semester: 'HK1',
    subject: 'Ngữ văn',
    target_type: 'score',
    target_value: 8.5,
    note: 'Nâng cao khả năng viết nghị luận',
    status: 'in_progress',
  },
];

export const SEED_ACHIEVEMENT_RECORDS: AchievementRecord[] = [
  {
    id: 'ach-quan-1',
    child_id: 'child-trung-quan',
    date: '2026-05-25',
    school_year: '2025-2026',
    category: 'academic',
    title: 'Học sinh Tiêu biểu Xuất sắc Lớp 5',
    description: 'Đạt danh hiệu hoàn thành xuất sắc các nội dung học tập và rèn luyện năm học 2025–2026',
    level: 'Cấp trường',
    result: 'Xuất sắc',
    organization: 'Trường Tiểu học',
  },
  {
    id: 'ach-quan-2',
    child_id: 'child-trung-quan',
    date: '2026-06-12',
    school_year: '2025-2026',
    category: 'certificate',
    title: 'Chứng chỉ Cambridge English A2 Flyers',
    description: 'Đạt 14/15 khiên bài thi quốc tế Cambridge Flyers',
    level: 'Quốc tế',
    result: '14 Shields (Xuất sắc)',
    organization: 'Cambridge Assessment English',
    score: '14/15',
  },
  {
    id: 'ach-quan-3',
    child_id: 'child-trung-quan',
    date: '2026-03-20',
    school_year: '2025-2026',
    category: 'competition',
    title: 'Giải Ba Olympic Tiếng Anh qua Internet (IOE)',
    description: 'Đạt giải Ba kỳ thi IOE cấp Quận khối 5',
    level: 'Cấp quận',
    result: 'Giải Ba',
    organization: 'Phòng GD&ĐT',
    rank: '3',
  },
  // Bé Hạ Băng milestone
  {
    id: 'ach-bang-1',
    child_id: 'child-ha-bang',
    date: '2026-06-01',
    school_year: '2025-2026',
    category: 'behavior',
    title: 'Bé Khỏe Bé Ngoan Tuần Lễ Thiếu Nhi',
    description: 'Tự lập xúc cơm và hòa đồng với bạn bè tại lớp mầm',
    level: 'Cấp trường',
    result: 'Bé Ngoan Xuất Sắc',
    organization: 'Trường Mầm Non Họa Mi',
  },
];

export const SEED_SCHOOL_YEARS: SchoolYearRecord[] = [
  {
    id: 'sy-quan-lop1',
    child_id: 'child-trung-quan',
    school_year: '2021-2022',
    grade: 'Lớp 1',
    class_name: '1A1',
    school_name: 'Tiểu học Tô Hiệu',
    homeroom_teacher: {
      name: 'Cô Nguyễn Thị Hoa',
      phone: '0912.111.222',
    },
    overall_score: 9.8,
    rank: 1,
    rank_total: 40,
    classification: 'Xuất sắc',
    teacher_feedback: 'Chăm ngoan, lễ phép, tiếp thu bài rất nhanh. Chữ viết tròn trịa, sạch đẹp.',
    status: 'completed',
    subject_scores: [
      { subject: 'Toán', term1_score: 10, term2_score: 10, final_score: 10, comment: 'Hoàn thành xuất sắc' },
      { subject: 'Tiếng Việt', term1_score: 9.5, term2_score: 9.8, final_score: 9.7, comment: 'Đọc diễn cảm tốt' },
      { subject: 'Tiếng Anh', term1_score: 9.8, term2_score: 9.8, final_score: 9.8, comment: 'Phát âm chuẩn' },
    ],
  },
  {
    id: 'sy-quan-lop2',
    child_id: 'child-trung-quan',
    school_year: '2022-2023',
    grade: 'Lớp 2',
    class_name: '2A1',
    school_name: 'Tiểu học Tô Hiệu',
    homeroom_teacher: {
      name: 'Cô Hoàng Thu Thủy',
      phone: '0913.222.333',
    },
    overall_score: 9.7,
    rank: 1,
    rank_total: 41,
    classification: 'Xuất sắc',
    teacher_feedback: 'Ý thức tự giác cao, tích cực tham gia các hoạt động tập thể và phong trào lớp.',
    status: 'completed',
    subject_scores: [
      { subject: 'Toán', term1_score: 9.8, term2_score: 9.8, final_score: 9.8 },
      { subject: 'Tiếng Việt', term1_score: 9.5, term2_score: 9.6, final_score: 9.6 },
      { subject: 'Tiếng Anh', term1_score: 9.8, term2_score: 9.8, final_score: 9.8 },
    ],
  },
  {
    id: 'sy-quan-lop3',
    child_id: 'child-trung-quan',
    school_year: '2023-2024',
    grade: 'Lớp 3',
    class_name: '3A2',
    school_name: 'Tiểu học Tô Hiệu',
    homeroom_teacher: {
      name: 'Thầy Lê Anh Tuấn',
      phone: '0914.333.444',
    },
    overall_score: 9.6,
    rank: 2,
    rank_total: 42,
    classification: 'Xuất sắc',
    teacher_feedback: 'Học đều tất cả các môn, tư duy toán học logic và sáng tạo.',
    status: 'completed',
    subject_scores: [
      { subject: 'Toán', final_score: 9.8 },
      { subject: 'Tiếng Việt', final_score: 9.3 },
      { subject: 'Tiếng Anh', final_score: 9.7 },
      { subject: 'Tin học', final_score: 10 },
    ],
  },
  {
    id: 'sy-quan-lop4',
    child_id: 'child-trung-quan',
    school_year: '2024-2025',
    grade: 'Lớp 4',
    class_name: '4A2',
    school_name: 'Tiểu học Tô Hiệu',
    homeroom_teacher: {
      name: 'Cô Bùi Bích Phương',
      phone: '0915.444.555',
    },
    overall_score: 9.5,
    rank: 2,
    rank_total: 42,
    classification: 'Xuất sắc',
    teacher_feedback: 'Có tố chất thi học sinh giỏi môn Toán và Tiếng Anh. Trách nhiệm làm lớp phó tốt.',
    status: 'completed',
    subject_scores: [
      { subject: 'Toán', final_score: 9.7 },
      { subject: 'Tiếng Việt', final_score: 9.2 },
      { subject: 'Tiếng Anh', final_score: 9.6 },
      { subject: 'Khoa học & Lịch sử', final_score: 9.5 },
    ],
  },
  {
    id: 'sy-quan-lop5',
    child_id: 'child-trung-quan',
    school_year: '2025-2026',
    grade: 'Lớp 5',
    class_name: '5A3',
    school_name: 'Tiểu học Tô Hiệu',
    homeroom_teacher: {
      name: 'Cô Đặng Thị Lan',
      phone: '0916.555.666',
    },
    overall_score: 9.6,
    rank: 1,
    rank_total: 42,
    classification: 'Xuất sắc',
    teacher_feedback: 'Hoàn thành xuất sắc chương trình Tiểu học. Đạt nhiều giải thưởng thi học sinh giỏi.',
    status: 'completed',
    subject_scores: [
      { subject: 'Toán', final_score: 9.8 },
      { subject: 'Tiếng Việt', final_score: 9.4 },
      { subject: 'Tiếng Anh', final_score: 9.7 },
      { subject: 'Tin học & Khoa học', final_score: 9.6 },
    ],
  },
  {
    id: 'sy-quan-lop6',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    grade: 'Lớp 6',
    class_name: '6A5',
    school_name: 'THCS Tô Hiệu',
    homeroom_teacher: {
      name: 'Cô Trần Thu Hà',
      phone: '0912.345.678',
      email: 'thuha.nguvan@tohieu.edu.vn',
    },
    overall_score: 9.3,
    rank: 2,
    rank_total: 42,
    classification: 'Đang học',
    teacher_feedback: 'Thích nghi nhanh với môi trường THCS, tích cực xây dựng bài.',
    status: 'current',
    subject_scores: [
      { subject: 'Toán', final_score: 9.5, comment: 'Tiếp thu nhanh' },
      { subject: 'Ngữ văn', final_score: 8.5, comment: 'Cần trau chuốt lời văn' },
      { subject: 'Tiếng Anh', final_score: 9.5, comment: 'Vốn từ tốt' },
      { subject: 'KHTN', final_score: 9.0, comment: 'Hiểu bài' },
      { subject: 'Lịch sử & Địa lí', final_score: 9.0 },
    ],
  },
];

export const SEED_TEACHERS: TeacherContact[] = [
  {
    id: 'teacher-1',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    class_name: '6A5',
    name: 'Cô Trần Thu Hà',
    role: 'homeroom',
    subject: 'GVCN & Môn Ngữ văn',
    phone: '0912.345.678',
    zalo_phone: '0912345678',
    email: 'thuha.nguvan@tohieu.edu.vn',
    notes: 'Liên hệ qua Zalo sau 17h hoặc số cá nhân khi có việc gấp.',
    parent_notes: 'Cô phụ trách chủ nhiệm, rất tận tâm và nhiệt tình.',
  },
  {
    id: 'teacher-2',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    class_name: '6A5',
    name: 'Thầy Nguyễn Văn Nam',
    role: 'subject',
    subject: 'Môn Toán',
    phone: '0987.654.321',
    zalo_phone: '0987654321',
    email: 'namnv.toan@tohieu.edu.vn',
    notes: 'Học sinh nộp bài tập hình học trước thứ 5 hàng tuần.',
    parent_notes: 'Thầy rèn tính tư duy logic rất tốt.',
  },
  {
    id: 'teacher-3',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    class_name: '6A5',
    name: 'Cô Lê Thị Mai',
    role: 'subject',
    subject: 'Môn Tiếng Anh',
    phone: '0903.112.233',
    zalo_phone: '0903112233',
    email: 'maielt@tohieu.edu.vn',
    notes: 'Lớp chuẩn bị bài thuyết trình Unit 3 vào tuần tới.',
  },
  {
    id: 'teacher-4',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    class_name: '6A5',
    name: 'Thầy Đặng Quốc Hùng',
    role: 'subject',
    subject: 'Môn KHTN (Vật lí & Hóa học)',
    phone: '0978.555.666',
    notes: 'Mang kính bảo hộ và sổ thực hành phòng thí nghiệm.',
  },
  {
    id: 'teacher-5',
    child_id: 'child-trung-quan',
    school_year: '2026-2027',
    class_name: '6A5',
    name: 'Cô Phạm Thúy Nga',
    role: 'tutor',
    subject: 'Toán Nâng Cao & Bồi Dưỡng',
    phone: '0934.888.999',
    zalo_phone: '0934888999',
    notes: 'Lớp học tối T2 - T5 từ 19h15 tại Trung tâm Bồi dưỡng.',
  },
];

export const SEED_SUBJECTS: SubjectItem[] = [
  { id: 'sub-toan', name: 'Toán', code: 'TOAN', color: '#2563EB', icon: '📐', category: 'core', note: 'Toán học' },
  { id: 'sub-van', name: 'Ngữ văn', code: 'VAN', color: '#E11D48', icon: '📖', category: 'core', note: 'Văn học & Tiếng Việt' },
  { id: 'sub-anh', name: 'Tiếng Anh', code: 'TANN', color: '#EC4899', icon: '🌍', category: 'core', note: 'Tiếng Anh, nói chung' },
  { id: 'sub-khtn', name: 'KHTN', code: 'KHTN', color: '#059669', icon: '🔬', category: 'science', note: '(S): Sinh học | (Lí): Vật lí' },
  { id: 'sub-lsdl', name: 'Lịch sử & Địa lí', code: 'LSDL', color: '#D97706', icon: '🗺️', category: 'social', note: 'Lịch sử & Địa lí' },
  { id: 'sub-tin', name: 'Tin học', code: 'TIN', color: '#0891B2', icon: '💻', category: 'science', note: 'Tin học' },
  { id: 'sub-cn', name: 'Công nghệ', code: 'CN', color: '#6366F1', icon: '⚙️', category: 'science', note: 'Công nghệ' },
  { id: 'sub-gdcd', name: 'GDCD', code: 'GDCD', color: '#10B981', icon: '⚖️', category: 'social', note: 'Giáo dục công dân' },
  { id: 'sub-td', name: 'Thể dục', code: 'TD', color: '#EA580C', icon: '🏃', category: 'arts_sports', note: 'Giáo dục thể chất' },
  { id: 'sub-an', name: 'Âm nhạc', code: 'AN', color: '#8B5CF6', icon: '🎵', category: 'arts_sports', note: 'Âm nhạc' },
  { id: 'sub-mt', name: 'Mỹ thuật', code: 'MT', color: '#F43F5E', icon: '🎨', category: 'arts_sports', note: 'Mỹ thuật' },
  { id: 'sub-hdtn', name: 'HĐTN', code: 'HDTN', color: '#F59E0B', icon: '🌱', category: 'other', note: 'Hoạt động trải nghiệm hướng nghiệp' },
  { id: 'sub-kns', name: 'KNS', code: 'KNS', color: '#14B8A6', icon: '💡', category: 'other', note: 'Kỹ năng sống' },
  { id: 'sub-shl', name: 'SHL', code: 'SHL', color: '#64748B', icon: '👥', category: 'other', note: 'Sinh hoạt lớp' },
  { id: 'sub-cc', name: 'Chào cờ', code: 'CC', color: '#DC2626', icon: '🚩', category: 'other', note: 'Chào cờ đầu tuần' },
];

export const SEED_TIMETABLE_LEGEND: TimetableLegendItem[] = [
  { id: 'leg-1', code: 'TANN', note: 'Tiếng Anh, nói chung' },
  { id: 'leg-2', code: 'KNS', note: 'Kỹ năng sống' },
  { id: 'leg-3', code: 'SHL', note: 'Sinh hoạt lớp' },
  { id: 'leg-4', code: 'HĐTN', note: 'Hoạt động trải nghiệm hướng nghiệp' },
  { id: 'leg-5', code: 'CN', note: 'Công nghệ' },
  { id: 'leg-6', code: '(S) | (Lí)', note: 'Sinh học | Vật lí' },
];

export const SEED_SESSION_LOGS: ExtraClassSessionLog[] = [
  {
    id: 'log-1',
    extra_schedule_id: 'extra-toan',
    child_id: 'child-trung-quan',
    date: '2026-09-17',
    score: 9.5,
    max_score: 10,
    status: 'attended',
    teacher_comment: 'Hiểu bài nhanh, giải tốt bài đại số nâng cao số 4.',
    parent_note: 'Đã hoàn thành bài tập về nhà.',
  },
  {
    id: 'log-2',
    extra_schedule_id: 'extra-toan',
    child_id: 'child-trung-quan',
    date: '2026-09-14',
    score: 9.0,
    max_score: 10,
    status: 'attended',
    teacher_comment: 'Cần cẩn thận hơn ở bước quy đồng phân thức.',
  },
  {
    id: 'log-3',
    extra_schedule_id: 'extra-toan',
    child_id: 'child-trung-quan',
    date: '2026-09-10',
    score: 10,
    max_score: 10,
    status: 'attended',
    teacher_comment: 'Làm bài xuất sắc, trình bày sạch đẹp nhất lớp.',
  },
  {
    id: 'log-4',
    extra_schedule_id: 'extra-toan',
    child_id: 'child-trung-quan',
    date: '2026-09-07',
    score: 9.5,
    max_score: 10,
    status: 'attended',
    teacher_comment: 'Nắm chắc kiến thức phương trình bậc nhất.',
  },
  {
    id: 'log-5',
    extra_schedule_id: 'extra-tieng-anh',
    child_id: 'child-trung-quan',
    date: '2026-09-19',
    score: 9.5,
    max_score: 10,
    status: 'attended',
    teacher_comment: 'Phát âm chuẩn Unit 2, tự tin thuyết trình.',
  },
  {
    id: 'log-6',
    extra_schedule_id: 'extra-tieng-anh',
    child_id: 'child-trung-quan',
    date: '2026-09-16',
    score: 9.0,
    max_score: 10,
    status: 'attended',
    teacher_comment: 'Cần bổ sung thêm vốn từ vựng chủ đề môi trường.',
  },
];

export const SEED_HOMEWORK_TASKS: HomeworkTask[] = [
  {
    id: 'hw-1',
    child_id: 'child-trung-quan',
    date: '2026-09-21',
    due_date: '2026-09-22',
    subject: 'Toán',
    description: 'Bài tập 1, 2, 3 trang 24 SGK Toán tập 1 (Phần lũy thừa)',
    is_completed: false,
    priority: 'high',
  },
  {
    id: 'hw-2',
    child_id: 'child-trung-quan',
    date: '2026-09-21',
    due_date: '2026-09-22',
    subject: 'Ngữ văn',
    description: 'Soạn bài Thực hành tiếng Việt (Biện pháp tu từ so sánh)',
    is_completed: true,
    priority: 'normal',
  },
  {
    id: 'hw-3',
    child_id: 'child-trung-quan',
    date: '2026-09-21',
    due_date: '2026-09-23',
    subject: 'Tiếng Anh',
    description: 'Viết đoạn văn 80 từ về ngôi nhà mơ ước (Unit 2 Writing)',
    is_completed: false,
    priority: 'high',
  },
  {
    id: 'hw-4',
    child_id: 'child-trung-quan',
    date: '2026-09-21',
    due_date: '2026-09-24',
    subject: 'KHTN',
    description: 'Vẽ sơ đồ cấu tạo tế bào nhân thực vào vở bài tập',
    is_completed: false,
    priority: 'normal',
  },
];

export const SEED_DAILY_TEACHER_COMMENTS: DailyTeacherComment[] = [
  {
    id: 'dtc-1',
    child_id: 'child-trung-quan',
    date: '2026-09-21',
    teacher_id: 'teacher-1',
    teacher_name: 'Cô Trần Thu Hà',
    teacher_role: 'homeroom',
    source_type: 'school',
    subject: 'GVCN & Ngữ văn',
    category: 'praise',
    content: 'Hôm nay con tích cực phát biểu xây dựng bài thơ Mây và Sóng, câu trả lời phân tích cảm thụ văn học rất sâu sắc. Nhắc con mai mang theo sách bài tập để cô kiểm tra.',
    parent_acknowledged: true,
    created_at: '2026-09-21T11:30:00Z',
  },
  {
    id: 'dtc-2',
    child_id: 'child-trung-quan',
    date: '2026-09-21',
    teacher_id: 'teacher-5',
    teacher_name: 'Cô Phạm Thúy Nga',
    teacher_role: 'tutor',
    source_type: 'extra',
    subject: 'Toán Nâng Cao & Bồi Dưỡng',
    category: 'praise',
    content: 'Buổi học tối nay con làm bài kiểm tra 45 phút đạt 9.5 điểm! Nắm rất chắc phần tam giác đồng dạng và biểu thức đại số, làm bài logic cẩn thận.',
    score: 9.5,
    parent_acknowledged: true,
    created_at: '2026-09-21T20:45:00Z',
  },
  {
    id: 'dtc-3',
    child_id: 'child-trung-quan',
    date: '2026-09-21',
    teacher_name: 'Cô Nguyễn Thị Vân',
    teacher_role: 'subject',
    source_type: 'school',
    subject: 'Bán trú & Sinh hoạt',
    category: 'boarding',
    content: 'Trưa nay con ăn hết suất cơm và rau xanh, ngủ trưa đúng giờ. Chiều hoạt động thể thao vui vẻ hòa đồng với các bạn.',
    parent_acknowledged: false,
    created_at: '2026-09-21T13:15:00Z',
  },
  {
    id: 'dtc-4',
    child_id: 'child-trung-quan',
    date: '2026-09-20',
    teacher_id: 'teacher-2',
    teacher_name: 'Thầy Nguyễn Văn Nam',
    teacher_role: 'subject',
    source_type: 'school',
    subject: 'Toán',
    category: 'homework',
    content: 'Con tập trung nghe giảng, làm bài tập tại lớp nhanh. Nhắc con về nhà nhớ làm nốt câu hình học bài 3 trang 42 SGK.',
    parent_acknowledged: true,
    created_at: '2026-09-20T16:20:00Z',
  },
  {
    id: 'dtc-5',
    child_id: 'child-trung-quan',
    date: '2026-09-20',
    teacher_name: 'Thầy Peter Robinson',
    teacher_role: 'tutor',
    source_type: 'extra',
    subject: 'Tiếng Anh Giao Tiếp (IELTS Junior)',
    category: 'praise',
    content: 'Quan was exceptionally active during the debate today. Excellent pronunciation and rich vocabulary on environmental topics!',
    score: 9.0,
    parent_acknowledged: true,
    created_at: '2026-09-20T19:30:00Z',
  },
];

export const SEED_ACADEMIC_MILESTONES: AcademicMilestone[] = [
  {
    id: 'milestone-survey-1',
    child_id: 'child-trung-quan',
    title: 'Khảo sát Năng lực Đầu Năm Học',
    category: 'survey',
    date: '2026-09-12',
    status: 'completed',
    target_score: '>= 8.5',
    actual_score: '9.2',
    subjects: ['Toán', 'Ngữ văn', 'Tiếng Anh'],
    color: '#0284C7',
    description: 'Đánh giá phân loại lớp chọn chuyên đề học kỳ 1.',
    preparation_notes: 'Hoàn thành tốt đề cương ôn tập hè.',
  },
  {
    id: 'milestone-survey-sep',
    child_id: 'child-trung-quan',
    title: 'Kiểm tra Chuyên đề Khảo sát Tháng 9',
    category: 'survey',
    date: '2026-09-26',
    status: 'active',
    target_score: '>= 9.0',
    subjects: ['Toán bồi dưỡng', 'Tiếng Anh'],
    color: '#F59E0B',
    description: 'Khảo sát định kỳ sau 1 tháng vào năm học chính thức.',
    preparation_notes: 'Ôn kỹ phần Đại số chương 1 và cấu trúc ngữ pháp thì hoàn thành.',
  },
  {
    id: 'milestone-midterm-1',
    child_id: 'child-trung-quan',
    title: 'Thi Giữa Học Kỳ 1 (Midterm 1)',
    category: 'midterm',
    date: '2026-11-06',
    status: 'planned',
    target_score: '>= 9.0',
    subjects: ['Toán', 'Ngữ văn', 'Tiếng Anh', 'KHTN'],
    color: '#8B5CF6',
    description: 'Kỳ thi tập trung tính điểm hệ số 2 quan trọng.',
    preparation_notes: 'Bắt đầu giải đề cương từ cuối tháng 10.',
  },
  {
    id: 'milestone-final-1',
    child_id: 'child-trung-quan',
    title: 'Thi Học Kỳ 1 Tập Trung (Final HK1)',
    category: 'final',
    date: '2026-12-22',
    status: 'planned',
    target_score: '>= 9.2 (Top 3 lớp)',
    subjects: ['Tất cả 8 môn thi'],
    color: '#EF4444',
    description: 'Thi học kỳ toàn diện, quyết định danh hiệu học sinh xuất sắc HK1.',
    preparation_notes: 'Cần phân bổ thời gian đều cho các môn Khoa học tự nhiên và Lịch sử Địa lý.',
  },
  {
    id: 'milestone-olympic-eng',
    child_id: 'child-trung-quan',
    title: 'Kỳ thi Olympic / HSG Tiếng Anh Cấp Quận',
    category: 'olympic',
    date: '2027-02-28',
    status: 'planned',
    target_score: 'Đạt Giải Ba trở lên',
    subjects: ['Tiếng Anh chuyên sâu'],
    color: '#10B981',
    description: 'Kỳ thi chọn học sinh giỏi cấp quận khối THCS.',
    preparation_notes: 'Luyện đề thi các năm trước cùng thầy Peter Robinson.',
  },
  {
    id: 'milestone-final-2',
    child_id: 'child-trung-quan',
    title: 'Thi Học Kỳ 2 & Tổng Kết Năm Học (Final HK2)',
    category: 'final',
    date: '2027-05-15',
    status: 'planned',
    target_score: '>= 9.3',
    subjects: ['Tất cả các môn'],
    color: '#EC4899',
    description: 'Xét khen thưởng học sinh Giỏi & Xuất sắc toàn năm học 2026-2027.',
    preparation_notes: 'Kế hoạch nước rút từ giữa tháng 4.',
  },

  // Bé Hạ Băng - Mầm non
  {
    id: 'milestone-bang-1',
    child_id: 'child-ha-bang',
    title: 'Biểu Diễn Năng Khiếu Văn Nghệ Mầm Non',
    category: 'certificate',
    date: '2026-11-20',
    status: 'planned',
    target_score: 'Bé múa dẻo và tự tin',
    subjects: ['Múa', 'Hát mầm non'],
    color: '#EC4899',
    description: 'Biểu diễn chào mừng ngày Nhà giáo Việt Nam tại trường Họa Mi.',
  },
];

